name: VHI semanal + email

on:
  schedule:
    - cron: '0 13 * * 1'   # Segunda 13:00 UTC = 10:00 BRT
  workflow_dispatch:
    inputs:
      attachments:
        description: 'Imagens a embutir (um por linha). Se vazio, usa o padrão.'
        required: false
        type: string
        default: |
          vhi_images/combined_Minas_Gerais_Sao_Paulo.png
          vhi_images/combined_Rondonia_Espirito_Santo.png
          vhi_images/Bahia_combined.png
      VHI_WEEK:
        description: 'Forçar semana (1–53). Se vazio, usa ISO atual (BRT).'
        required: false
        type: string
      VHI_MAX_LOOKBACK:
        description: 'Máx. semanas p/ voltar (default 10).'
        required: false
        type: string

jobs:
  run-and-email:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: 'utf-8'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
      DEFAULT_ATTACHMENTS: |
        vhi_images/combined_Minas_Gerais_Sao_Paulo.png
        vhi_images/combined_Rondonia_Espirito_Santo.png
        vhi_images/Bahia_combined.png

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests pillow
          fi

      - name: Run VHI script
        env:
          VHI_WEEK: ${{ github.event.inputs.VHI_WEEK }}
          VHI_MAX_LOOKBACK: ${{ github.event.inputs.VHI_MAX_LOOKBACK }}
        run: |
          python src/data/codigo9_dadosVhi.py
          echo "Arquivos gerados:"
          ls -la vhi_images || true

      - name: Read week number
        run: |
          if [ -f vhi_images/week.txt ]; then
            echo "WEEK=$(cat vhi_images/week.txt)" >> $GITHUB_ENV
          else
            echo "WEEK=?" >> $GITHUB_ENV
          fi

      # Cria um arquivo com a lista de caminhos, robusto a colagens/sem quebras
      - name: Build attachments list file (robust)
        env:
          INPUT_ATTACHMENTS: ${{ github.event.inputs.attachments }}
          DEFAULT_ATTACHMENTS_STEP: ${{ env.DEFAULT_ATTACHMENTS }}
        run: |
          # 1) fonte: inputs ou default
          if [ -n "$INPUT_ATTACHMENTS" ]; then
            SRC="$INPUT_ATTACHMENTS"
          else
            SRC="$DEFAULT_ATTACHMENTS_STEP"
          fi

          # 2) normaliza CRLF -> LF e salva bruto
          printf '%s' "$SRC" | tr -d '\r' > attach_raw.txt

          # 3) extrai TODOS os caminhos com regex (mesmo colados)
          #    pega sequências que começam com vhi_images/ e terminam em .png
          grep -Eo 'vhi_images/[^[:space:]]+\.png' attach_raw.txt > attach_list.txt

          # 4) se por algum motivo não captou nada, cai no fallback linha a linha
          if [ ! -s attach_list.txt ]; then
            awk 'NF' attach_raw.txt > attach_list.txt
          fi

          echo "----- attach_list.txt -----"
          nl -ba attach_list.txt || true

      # Constrói o HTML com imagens embutidas em Base64 (sem anexos)
      - name: Build Base64 HTML
        run: |
          i=0
          HTML=""
          while IFS= read -r path; do
            [ -z "$path" ] && continue
            i=$((i+1))
            case $i in
              1) ALT="Minas Gerais acima de Sao Paulo" ;;
              2) ALT="Rondonia acima de Espirito Santo" ;;
              3) ALT="Bahia" ;;
              *) ALT="$(basename "$path")" ;;
            esac

            if [ -f "$path" ]; then
              DATA=$(base64 -w 0 "$path")
              HTML="${HTML}<p><strong>${ALT}</strong></p><img src=\"data:image/png;base64,${DATA}\" alt=\"${ALT}\" style=\"max-width:100%;height:auto;border:1px solid #ddd\"/><br/><br/>"
            else
              HTML="${HTML}<p><strong>${ALT}</strong> (arquivo não encontrado: ${path})</p>"
            fi
          done < attach_list.txt

          {
            echo "IMAGES_HTML<<EOF"
            printf "%s" "$HTML"
            echo
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Upload images as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: vhi_images
          path: vhi_images/*.png

      - name: Send email (HTML com imagens embutidas) - SSL 465
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          subject: "VHI - imagens semana ${{ env.WEEK }}"
          secure: true
          html_body: |
            <div style="font-family:system-ui,Segoe UI,Arial,sans-serif;">
              <p><strong>VHI semanal (semana ${{ env.WEEK }})</strong></p>
              ${{ env.IMAGES_HTML }}
              <p style="color:#666;font-size:12px;">Envio automático – GitHub Actions.</p>
            </div>
          # Caso queira também anexar os PNGs além do inline, descomente:
          # attachments: |
          #   $(cat attach_list.txt)
