name: VHI semanal + email

on:
  schedule:
    # Segunda 13:00 UTC = 10:00 BRT
    - cron: '0 13 * * 1'
  workflow_dispatch:
    inputs:
      attachments:
        description: 'Arquivos a anexar (um por linha)'
        required: false
        type: string
        default: |
          vhi_images/combined_Minas_Gerais_Sao_Paulo.png
          vhi_images/combined_Rondonia_Espirito_Santo.png
          vhi_images/Bahia_combined.png
      VHI_WEEK:
        description: 'Forçar semana (1-53). Se vazio, usa ISO atual (BRT).'
        required: false
        type: string
      VHI_MAX_LOOKBACK:
        description: 'Máx. de semanas para voltar (default 10).'
        required: false
        type: string

jobs:
  run-and-email:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: 'utf-8'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
      # >>> Lista padrão de anexos (edite aqui quando quiser) <<<
      DEFAULT_ATTACHMENTS: |
        vhi_images/combined_Minas_Gerais_Sao_Paulo.png
        vhi_images/combined_Rondonia_Espirito_Santo.png
        vhi_images/Bahia_combined.png

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests pillow
          fi

      - name: Run VHI script
        env:
          # inputs de workflow_dispatch (se não vierem, ficam vazios)
          VHI_WEEK: ${{ github.event.inputs.VHI_WEEK }}
          VHI_MAX_LOOKBACK: ${{ github.event.inputs.VHI_MAX_LOOKBACK }}
        run: |
          python src/data/codigo9_dadosVhi.py
          echo "Arquivos gerados:"
          ls -la vhi_images || true

      - name: Read week number
        id: week
        run: |
          if [ -f vhi_images/week.txt ]; then
            echo "WEEK=$(cat vhi_images/week.txt)" >> $GITHUB_ENV
          else
            echo "WEEK=?" >> $GITHUB_ENV
          fi

      # (opcional) manter as imagens como artefato
      - name: Upload images as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: vhi_images
          path: vhi_images/*.png

      - name: Send email with attachments
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          subject: "VHI - imagens semana ${{ env.WEEK }}"
          secure: starttls
          convert_markdown: true
          body: |
            **VHI semanal (semana ${{ env.WEEK }})**

            Seguem as composições finais em anexo.
          # Se o usuário passar anexos no "Run workflow", usa-os; senão, usa a lista padrão
          attachments: ${{ github.event.inputs.attachments != '' && github.event.inputs.attachments || env.DEFAULT_ATTACHMENTS }}
